version: '3.8'

services:

  # ─────────────────────────────────────────
  # Database for user-service
  # ─────────────────────────────────────────
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"                     # host port 5433 → container port 5432
                                        # WHY different port: all 3 are PostgreSQL, all use
                                        # 5432 internally. But your machine can't have three
                                        # things on the same host port. So we map differently:
                                        # user-db    → localhost:5433
                                        # product-db → localhost:5434
                                        # order-db   → localhost:5435
    volumes:
      - user-db-data:/var/lib/postgresql/data

  # ─────────────────────────────────────────
  # Database for product-service
  # ─────────────────────────────────────────
  product-db:
    image: postgres:15
    container_name: product-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5434:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data

#   # ─────────────────────────────────────────
#   # Database for order-service
#   # ─────────────────────────────────────────
#   order-db:
#     image: postgres:15
#     container_name: order-db
#     environment:
#       POSTGRES_DB: orderdb
#       POSTGRES_USER: testuser
#       POSTGRES_PASSWORD: testpass
#     ports:
#       - "5435:5432"
#     volumes:
#       - order-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:
  product-db-data:
#   order-db-data: