spring.application.name=user-service
server.port=8081

# Each microservice has its OWN database — this is the core of database-per-service pattern
spring.datasource.url=jdbc:postgresql://localhost:5433/userdb
spring.datasource.username=testuser
spring.datasource.password=testpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=ThisIsAStrongSecretKeyForECommerceJWT1234567890ABCDEF
jwt.expiration-ms=86400000

