spring.application.name=order-service
server.port=8083

# Order service owns orderdb
spring.datasource.url=jdbc:postgresql://localhost:5435/orderdb
spring.datasource.username=testuser
spring.datasource.password=testpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=ThisIsAStrongSecretKeyForECommerceJWT1234567890ABCDEF
jwt.expiration-ms=86400000

# Feign client URL for product-service
product.service.url=http://localhost:8082